language: cpp
dist: bionic
osx_image: xcode10.2
before_install:
- |-
    case $TRAVIS_OS_NAME in
      windows)
        choco install -y make mingw
        CXXFLAGS = "-D__USE_MINGW_ANSI_STDIO=1"
    esac
compiler:
- gcc
- clang
os:
- windows
branches:
- master
- development
